-- Community roles migration: department heads, invite-gated applications,
-- and suspension — layered on top of the existing profiles/departments
-- tables. Safe to run more than once.
--
-- Roles:
--   * Head Admin  — identified purely by ADMIN_EMAILS (unchanged), controls everything.
--   * Department Head — a profiles row with role = 'department_head' and a
--     department_id. Can onboard applicants (via one-time invite links) and
--     suspend/unsuspend members within their own department only.
--   * Member — default role.
--
-- All privileged reads/writes go through /api/roles.js using the
-- service-role key (same pattern as the rest of the backend), so RLS below
-- is a defense-in-depth layer, not the primary gate.

create extension if not exists pgcrypto;

-- Safety net: this migration assumes community_schema.sql (profiles) and
-- schema.sql (departments) have already been run. If either hasn't, create
-- the minimal table here so this file never fails regardless of order.
create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  bio text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.profiles enable row level security;

create table if not exists public.departments(
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  icon text default '✦',
  contact_email text,
  display_order integer default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);
alter table public.departments enable row level security;
drop policy if exists "public read active departments" on public.departments;
create policy "public read active departments" on public.departments for select using(is_active = true);

alter table public.profiles add column if not exists role text not null default 'member';
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('member','department_head'));

alter table public.profiles add column if not exists department_id uuid references public.departments(id) on delete set null;
alter table public.profiles add column if not exists is_suspended boolean not null default false;
alter table public.profiles add column if not exists suspended_at timestamptz;
alter table public.profiles add column if not exists suspended_by uuid references auth.users(id);

create index if not exists profiles_department_idx on public.profiles(department_id);
create index if not exists profiles_role_idx on public.profiles(role);

drop policy if exists "public read profiles" on public.profiles;
drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select to authenticated using(auth.uid() = id);
drop policy if exists "users manage own profile" on public.profiles;
drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile" on public.profiles for insert to authenticated
with check (auth.uid() = id and role = 'member' and department_id is null and is_suspended = false and suspended_at is null and suspended_by is null);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update to authenticated
using (auth.uid() = id) with check (auth.uid() = id);

-- Guard rail: a member should never be able to grant themselves head
-- privileges or clear their own suspension via a direct client-side
-- Supabase call (the existing "users manage own profile" policy otherwise
-- allows full writes to their own row). Only the service-role backend
-- (used by /api/roles.js) may change these columns.
create or replace function public.protect_profile_privileged_columns()
returns trigger language plpgsql as $$
begin
  if auth.role() is distinct from 'service_role' then
    if tg_op = 'INSERT' then
      new.role := 'member';
      new.department_id := null;
      new.is_suspended := false;
      new.suspended_at := null;
      new.suspended_by := null;
    else
      new.role := old.role;
      new.department_id := old.department_id;
      new.is_suspended := old.is_suspended;
      new.suspended_at := old.suspended_at;
      new.suspended_by := old.suspended_by;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_privileged_columns on public.profiles;
create trigger protect_profile_privileged_columns
before insert or update on public.profiles
for each row execute function public.protect_profile_privileged_columns();

-- One-time invite links generated by a department head (or the head admin)
-- so applicants can only join a department they were personally invited to.
create table if not exists public.department_invites(
  id uuid primary key default gen_random_uuid(),
  token text unique not null,
  department_id uuid not null references public.departments(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  applicant_name text,
  applicant_email text,
  status text not null default 'pending' check (status in ('pending','used','revoked')),
  created_at timestamptz default now(),
  expires_at timestamptz,
  used_at timestamptz,
  used_by uuid references auth.users(id)
);

create index if not exists department_invites_token_idx on public.department_invites(token);
create index if not exists department_invites_department_idx on public.department_invites(department_id);

alter table public.department_invites enable row level security;
-- No anon/authenticated policies are defined on purpose: every read/write
-- happens server-side through /api/roles.js with the service-role key,
-- which bypasses RLS. This keeps invite tokens and applicant details out of
-- reach of direct client-side Supabase calls.
grant all on public.department_invites to service_role;
